[api]
flowise_url = "https://flowise-renataraev64.amvera.io/api/v1/prediction/4a4a3f5c-9ebf-4243-8d4f-b3b69dd57313"

[database]
path = "user_database.json"
chat_history_path = "chat_history.json"

[admin]
username = "admin"
password = "your_secure_password"
